Add easy way to redeem max
aloelabs/aloe-ii pull request #146
Opened 2023-09-07 04:29 UTC by haydenshively

Builds on #145. Makes it easy to redeemMax in core, and easy to repayMax in periphery.

2023-09-07 04:54 UTC, IanWoodard approved these changes

2023-09-07 04:55 UTC, IanWoodard requested changes

2023-09-07 04:55 UTC, IanWoodard commented on periphery/src/Router.sol
> +     */
Fix?

2023-09-07 05:02 UTC, IanWoodard approved these changes

2023-09-08 04:40 UTC, aneesh1 approved these changes

2023-09-08 05:40 UTC, merged